modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT"

[[mods]]
modId = "kariti_mod"
version = "1.0.0"
displayName = "Kariti Mod"
description = '''
Карити — союзник, который охотится на Верити. Появляется рядом с игроком при входе в мир
и атакует любую сущность с "verity" в названии.
'''

[[dependencies.kariti_mod]]
    modId = "forge"
    mandatory = true
    versionRange = "[47,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.kariti_mod]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.20.1,1.21)"
    ordering = "NONE"
    side = "BOTH"
